services:
  mm_product_api:
    build:
      context: .
      dockerfile: Dockerfile
      # not need to define
    command: ["run", "start:prod"]
    # env_file:
    #   - .env
    environment:
      - NODE_ENV=production
      - PORT=30000
      - DATABASE_URL=postgresql://user:password@db:5432/shop-product-docker
    ports:
      - "30000:30000"

  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shop-product-docker
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      