name: CI WorkFlow

on: 
    pull_request:
        branches:
        - main # trigger github event

# on: workflow_dispatch // manual trigger
        
jobs:
    build: # job name
        runs-on: ubuntu-latest # can use custom runners too
        steps:
            - name: Checkout code # git clone
              uses: actions/checkout@v5 # checkout code

            - name: Set up Node
              uses: actions/setup-node@v5
              with:
                node-version: '24'

            - name: Install dependencies
              run: npm install
            #   working-directory: ./frontend # change directory

            - name: Build the project
              run: npm run build

            - name: Run tests
              run: npm run test