name: CI WorkFlow

on:
  pull_request:
    branches:
      - main # trigger github event
    # types: [opened, synchronize, reopened, closed]

# on: workflow_dispatch // manual trigger

jobs:
  build: # job name
    runs-on: ubuntu-latest # can use custom runners too
    steps:
      - name: Checkout code # git clone
        uses: actions/checkout@v5 # checkout code

      - name: Set up Node
        uses: actions/setup-node@v5
        with:
          node-version: '24'

      - name: Install dependencies
        run: npm install
      #   working-directory: ./frontend # change directory

      - name: Cache node modules
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package.json', '**/package-lock.json') }}

      - name: Build the project
        run: npm run build

  unit-tests:
    runs-on: ubuntu-latest
    needs: build # job dependency
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Node
        uses: actions/setup-node@v5
        with:
          node-version: '24'

      - name: Cache node modules
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package.json', '**/package-lock.json') }}

      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm install

      - name: Run unit tests
        run: npm run test
