name: CI WorkFlow

on: 
    pull_request:
        branches:
        - main
        
jobs: 
    build: # job name
        runs-on: ubuntu-latest # we can use custom runners too

        steps:
         - run: echo "Hello World from GitHub Actions" # step 1
