name: Common Jobs

on:
  workflow_call:
    secrets:
      postgres_username:
        required: true


      postgres_password:
        required: true
    inputs:
      is_release:
        required: true
        type: boolean
        default: false
    outputs:
      is_success:
        description: 'Indicates if the jobs were successful'
        value: ${{ jobs.test.result }}


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js environment
        id: setup-node
        uses: ./.github/actions/node-setup-action
        with:
          node-version: '20'

      - name: prisma generate
        if: steps.setup-node.outcome == 'success'
        run: npx prisma generate

      - name: Build the project
        run: npm run build

  lint:
    if: inputs.is_release == false
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js environment
        uses: ./.github/actions/node-setup-action
        with:
          node-version: '20'

      - name: Build the project
        run: npm run lint

  test:
    env:
      DATABASE_URL: postgres://${{ secrets.postgres_username }}:${{ secrets.postgres_password }}@localhost:5432/shop-product-docker
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: ${{ secrets.postgres_username }}
          POSTGRES_PASSWORD: ${{ secrets.postgres_password }}
          POSTGRES_DB: shop-product-docker
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    

    needs:
      - build
    steps:
      - name: Setup Node.js environment
        id: setup-node
        uses: ./.github/actions/node-setup-action
        with:
          node-version: '20'
        
      - name: prisma generate
        if: steps.setup-node.outcome == 'success'
        run: npx prisma

      - name: prisma migrate deploy
        run: npm run db:migrate

      - name: Run tests
        run: npm test

      - name: Run test coverage
        run: npm run test:cov

      - name: Upload coverage to Codecov
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage
