name: Release Workflow

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - release/**

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:

  common-jobs:
    uses: ./.github/workflows/common-jobs.yaml
    secrets:
      postgres_username: ${{ secrets.POSTGRES_USENAME }}
      postgres_password: ${{ secrets.POSTGRES_PASSWORD }}
    with:
      is_release: true

  dockernize:
    needs:
      - common-jobs
    runs-on: ubuntu-latest
    steps:

      - name: Output success status
        run: |
          echo "Common jobs success status: ${{ needs.common-jobs.outputs.is_success }}"
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker buildx build --platform linux/amd64 -t mmshop-product-api:latest . --load
    
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push Docker image to Docker Hub
        run: |
          docker tag mmshop-product-api ${{ secrets.DOCKER_HUB_USERNAME }}/mmshop-product-api:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/mmshop-product-api:latest